### ISSUE TITLE
Error when submitting contest - PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder-contest-server#7]

**Comment by nicosantangelo** [comment]
I need a bit more info to tackle this.

How did it happen?
With which payload?
Did it happen testing a scene? if not, where?

I'm pretty sure I can fix it by setting the limit prop on bodyParser json like this:
`bodyParser.json({ limit: '50mb' })`

but I don't want to fix it in the dark, if possible

**Comment by nicosantangelo** [comment]
Tracked here for a front-end fix: https://github.com/decentraland/builder/pull/291
